services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: LifeSync
    container_name: lifesync-database
    volumes:
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/database/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 25s
      retries: 25
    networks:
      - life-network

  backend:
    build: ./backend/GoCode/
    environment:
      DB_SERVER: lifesync-database
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: LifeSync
      APP_PORT: "8080"
    container_name: lifesync-backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - life-network

  web:
    image: httpd:latest
    container_name: lifesync-web
    ports:
      - 8081:80
    volumes:
      - ./website:/usr/local/apache2/htdocs/
    networks:
      - life-network

networks:
  life-network:
    driver: bridge
